//
//  RecastNavigationKit.h
//  RecastNavigationExample
//
//  Created by Tatsuya Ogawa on 2025/12/24.
//

#import <Foundation/Foundation.h>
#import <simd/simd.h>
#import <stdint.h>

NS_ASSUME_NONNULL_BEGIN

@class RCNavPath;

@interface RecastNavMesh : NSObject

/// Load a NavMesh (data generated by dtNavMeshCreateParams)
- (instancetype)initWithNavMeshData:(NSData *)data;

/// Initialize taking ownership of raw memory returned by dtCreateNavMeshData() (DT_TILE_FREE_DATA)
- (instancetype)initWithNavMeshBytes:(unsigned char *)bytes length:(int)length;

/// Pathfinding (returns polygon refs and the straight path together)
- (nullable RCNavPath *)findPathResultFrom:(vector_float3)start
                                        to:(vector_float3)end;

/// Find nearest point on the NavMesh (nearest polygon search)
- (vector_float3)findNearestPoint:(vector_float3)point;

/// Triangle vertex list of the NavMesh (xyz xyz ...). outVertexCount is the number of vertices.
- (NSData *)navMeshTriangleVerticesWithVertexCount:(int *)outVertexCount;

@end

/// Wrapper that holds dtPolyRef array and the straight path
@interface RCNavPath : NSObject

/// Number of dtPolyRef entries
@property (nonatomic, readonly) int polyCount;

/// Number of points in the straight path
@property (nonatomic, readonly) int pointCount;

/// Get the point at the specified index
- (vector_float3)pointAtIndex:(int)index;

/// Get the dtPolyRef at the specified index
- (uint64_t)polyRefAtIndex:(int)index;

@end

NS_ASSUME_NONNULL_END
